# Generated by Django 5.2.4 on 2025-10-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0002_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nome_departamento',
            new_name='nome',
        ),
    ]
