# Generated by Django 5.2.4 on 2025-10-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0003_rename_nome_departamento_departamento_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ano',
            new_name='depart',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
    ]
