# Generated by Django 5.2.4 on 2025-10-31 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0004_rename_ano_usuario_depart_remove_usuario_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coordenacao.departamento'),
        ),
    ]
