# Generated by Django 5.2.4 on 2025-11-05 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0005_alter_usuario_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coordenacao.curso'),
        ),
    ]
