# Generated by Django 5.2.4 on 2025-11-14 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0006_usuario_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('cordenacao', 'cordenacao'), ('dac', 'dac'), ('presidente', 'professores'), ('estudante', 'estudante'), ('area_cientifica', 'area_cientifica'), ('tutor', 'tutor')], max_length=20),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('resumo', models.FileField(blank=True, null=True, upload_to='resumos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_tutor', 'Aguardando Aprovação do Tutor'), ('aprovado_tutor', 'Aprovado pelo Tutor'), ('rejeitado_tutor', 'Rejeitado pelo Tutor'), ('aguardando_coordenacao', 'Aguardando Coordenação'), ('aprovado', 'Tema Aprovado'), ('rejeitado_coordenacao', 'Rejeitado pela Coordenação')], default='pendente', max_length=40)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(limit_choices_to={'perfil': 'estudante'}, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to=settings.AUTH_USER_MODEL)),
                ('tutor_indicado', models.ForeignKey(blank=True, limit_choices_to={'perfil': 'tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_orientados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
