# Generated by Django 5.2.4 on 2025-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0007_alter_usuario_perfil_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='requerimento',
            field=models.FileField(blank=True, null=True, upload_to='requer/'),
        ),
    ]
