# Generated by Django 5.2.7 on 2025-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0008_tema_requerimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='status',
        ),
        migrations.AddField(
            model_name='tema',
            name='status_coordenacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado pela coordenação'), ('rejeitado', 'Rejeitado pela coordenação')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='tema',
            name='status_final',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=15),
        ),
        migrations.AddField(
            model_name='tema',
            name='status_tutor',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado pelo tutor'), ('rejeitado', 'Rejeitado pelo tutor')], default='pendente', max_length=15),
        ),
    ]
