# Generated by Django 5.2.4 on 2025-12-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0010_mensagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
