# Generated by Django 5.2.4 on 2025-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0012_recomendacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
