# Generated by Django 5.2.4 on 2026-01-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordenacao', '0013_recomendacao_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
